# Welcome to Jekyll!
#

# Configurações do Site
title: Vanité - Complexo de Beleza
description: |
  Conheça nosso serviços


owner: Vanité # Nome da Empresa
first_published: 2019 
email: contatovanite@gmail.com
url: "https://complexovanite.github.io" # coloque a URL aqui
social:
  twitter: https://twitter.com/complexovanite
  github: https://github.com/complextovanite
  facebook-official: https://www.facebook.com/complexovanite


# Build settings
markdown: kramdown
#sass:
#  style: compressed
